=== claytonbrown/serverless-application-model/samtranslator/validator/sam_schema/schema_new.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "AWSTemplateFormatVersion": {
      "enum": [
        "2010-09-09"
      ],
      "type": "string"
    },
    "Conditions": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "intrinsic"
        }
      },
      "type": "object"
    },
    "Description": {
      "description": "Template description",
      "maxLength": 1024,
      "type": "string"
    },
    "Globals": {
      "type": "object"
    },
    "Mappings": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Metadata": {
      "type": "object"
    },
    "Outputs": {
      "additionalProperties": false,
      "maxProperties": 60,
      "minProperties": 1,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Parameters": {
      "additionalProperties": false,
      "maxProperties": 50,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "$ref": "parameter.json#/definitions/Parameter"
        }
      },
      "type": "object"
    },
    "Resources": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "allOf": [
            {
              "$ref": "api.json#/definitions/AWS::Serverless::Api"
            },
            {
              "if": {
                "properties": {
                  "Type": {
                    "pattern": "^Custom::"
                  }
                }
              },
              "then": {
                "properties": {
                  "Type": {
                    "pattern": "^Custom::[a-zA-Z0-9]+$",
                    "patternError": "must use format Custom::X"
                  }
                }
              },
              "else": {
                "properties": {
                  "Type": {
                    "pattern": "^[a-zA-Z0-9]+::[a-zA-Z0-9]+::[a-zA-Z0-9]+$",
                    "patternError": "must use format X::Y::Z"
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "Type": {
                    "pattern": "^AWS::Serverless::"
                  }
                }
              },
              "then": {
                "properties": {
                  "Type": {
                    "enum": [
                      "AWS::Serverless::Api",
                      "AWS::Serverless::Application",
                      "AWS::Serverless::Function",
                      "AWS::Serverless::HttpApi",
                      "AWS::Serverless::WebSocketApi",
                      "AWS::Serverless::LayerVersion",
                      "AWS::Serverless::SimpleTable",
                      "AWS::Serverless::StateMachine",
                      "AWS::Serverless::Connector",
                      "AWS::Serverless::GraphQLApi"                    ]
                  }
                }
              }
            }
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "Transform": {
      "type": [
        "string",
        "array"
      ],
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "Resources"
  ],
  "type": "object"
}

=== claytonbrown/serverless-application-model/tests/translator/output/aws-cn/capacity_provider_with_intrinsics.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "CapacityProvider with intrinsic functions test",
  "Parameters": {
    "AllowedInstanceType": {
      "Default": "c5.xlarge",
      "Type": "String"
    },
    "Architecture": {
      "Default": "arm64",
      "Type": "String"
    },
    "ArchitecturesList": {
      "Default": "x86_64",
      "Type": "List<String>"
    },
    "CapacityProviderName": {
      "Default": "intrinsic-capacity-provider",
      "Type": "String"
    },
    "ExcludedInstanceTypeList": {
      "Default": "t2.micro,c5.xlarge",
      "Type": "List<String>"
    },
    "KmsKeyArn": {
      "Default": "arn:aws:kms:us-east-1:123456789012:key/abcd1234-ef56-gh78-ij90-klmnopqrstuv",
      "Type": "String"
    },
    "MaxVCpuCount": {
      "Default": 10,
      "Type": "Number"
    },
    "SecurityGroupId": {
      "Default": "sg-0a1e1457229da0f74",
      "Type": "String"
    },
    "SecurityGroupIdList": {
      "Default": "sg-0a1e1457229da0f74,sg-3b1f1457229da0f92",
      "Type": "List<AWS::EC2::SecurityGroup::Id>"
    },
    "SubnetId": {
      "Default": "subnet-01e6344879fd06036",
      "Type": "String"
    },
    "SubnetIdList": {
      "Default": "subnet-01e6344879fd06036,subnet-0136378879fd07039",
      "Type": "List<AWS::EC2::Subnet::Id>"
    },
    "TargetCPU": {
      "Default": 75.0,
      "Type": "Number"
    },
    "TargetMemory": {
      "Default": 81.2,
      "Type": "Number"
    }
  },
  "Resources": {
    "IntrinsicCapacityProvider": {
      "Properties": {
        "CapacityProviderName": {
          "Ref": "CapacityProviderName"
        },
        "CapacityProviderScalingConfig": {
          "MaxVCpuCount": {
            "Ref": "MaxVCpuCount"
          },
          "ScalingMode": "Manual",
          "ScalingPolicies": [
            {
              "PredefinedMetricType": "LambdaCapacityProviderAverageCPUUtilization",
              "TargetValue": {
                "Ref": "TargetCPU"
              }
            }
          ]
        },
        "InstanceRequirements": {
          "AllowedInstanceTypes": [
            {
              "Ref": "AllowedInstanceType"
            },
            {
              "Fn::Join": [
                ".",
                [
                  "c5",
                  "2xlarge"
                ]
              ]
            },
            "c5.large"
          ],
          "Architectures": [
            {
              "Ref": "Architecture"
            }
          ]
        },
        "KmsKeyArn": {
          "Ref": "KmsKeyArn"
        },
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "IntrinsicCapacityProviderOperatorRole",
              "Arn"
            ]
          }
        },
        "Tags": [
          {
            "Key": "Environment",
            "Value": {
              "Fn::Sub": "${AWS::StackName}-environment"
            }
          },
          {
            "Key": "Team",
            "Value": {
              "Fn::Sub": "${AWS::StackName}-team"
            }
          },
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": [
            {
              "Ref": "SecurityGroupId"
            }
          ],
          "SubnetIds": [
            {
              "Ref": "SubnetId"
            }
          ]
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "IntrinsicCapacityProviderOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-cn:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    },
    "IntrinsicCapacityProviderTwo": {
      "Properties": {
        "CapacityProviderScalingConfig": {
          "MaxVCpuCount": {
            "Ref": "MaxVCpuCount"
          },
          "ScalingMode": "Manual",
          "ScalingPolicies": [
            {
              "PredefinedMetricType": "LambdaCapacityProviderAverageCPUUtilization",
              "TargetValue": {
                "Ref": "TargetCPU"
              }
            }
          ]
        },
        "InstanceRequirements": {
          "Architectures": {
            "Ref": "ArchitecturesList"
          },
          "ExcludedInstanceTypes": {
            "Ref": "ExcludedInstanceTypeList"
          }
        },
        "KmsKeyArn": {
          "Ref": "KmsKeyArn"
        },
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "IntrinsicCapacityProviderTwoOperatorRole",
              "Arn"
            ]
          }
        },
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": {
            "Ref": "SecurityGroupIdList"
          },
          "SubnetIds": {
            "Ref": "SubnetIdList"
          }
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "IntrinsicCapacityProviderTwoOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-cn:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    }
  }
}

=== claytonbrown/serverless-application-model/tests/translator/output/aws-cn/separate_route53_recordset_group.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Conditions": {
    "CreateProdResources": {
      "Fn::Equals": [
        {
          "Ref": "EnvType"
        },
        "prod"
      ]
    }
  },
  "Description": "apigateway-2402\nSample SAM Template for apigateway-2402\n",
  "Parameters": {
    "EnvType": {
      "AllowedValues": [
        "prod",
        "test"
      ],
      "ConstraintDescription": "must specify prod or test.",
      "Default": "test",
      "Description": "Environment type.",
      "Type": "String"
    }
  },
  "Resources": {
    "ApiGatewayAdminOne": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "paths": {},
          "swagger": "2.0"
        },
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "Name": "App-Prod-Web",
        "Parameters": {
          "endpointConfigurationTypes": "REGIONAL"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "ApiGatewayAdminOneBasePathMapping": {
      "Properties": {
        "DomainName": {
          "Ref": "ApiGatewayDomainName5fe29fe649"
        },
        "RestApiId": {
          "Ref": "ApiGatewayAdminOne"
        },
        "Stage": {
          "Ref": "ApiGatewayAdminOneProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMapping"
    },
    "ApiGatewayAdminOneDeployment5f4fcb9347": {
      "Properties": {
        "Description": "RestApi deployment id: 5f4fcb9347315a0decaa8f0140aae89cde47f8d1",
        "RestApiId": {
          "Ref": "ApiGatewayAdminOne"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "ApiGatewayAdminOneProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "ApiGatewayAdminOneDeployment5f4fcb9347"
        },
        "MethodSettings": [
          {
            "HttpMethod": "*",
            "LoggingLevel": "Info",
            "ResourcePath": "/*"
          }
        ],
        "RestApiId": {
          "Ref": "ApiGatewayAdminOne"
        },
        "StageName": "Prod",
        "TracingEnabled": true
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "ApiGatewayAdminThree": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "paths": {},
          "swagger": "2.0"
        },
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "Name": "App-Prod-Web",
        "Parameters": {
          "endpointConfigurationTypes": "REGIONAL"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "ApiGatewayAdminThreeBasePathMapping": {
      "Properties": {
        "DomainName": {
          "Ref": "ApiGatewayDomainName41bfc7f9c4"
        },
        "RestApiId": {
          "Ref": "ApiGatewayAdminThree"
        },
        "Stage": {
          "Ref": "ApiGatewayAdminThreeProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMapping"
    },
    "ApiGatewayAdminThreeDeployment6688e0289c": {
      "Properties": {
        "Description": "RestApi deployment id: 6688e0289c1446101169a6ba165a416cecf813b6",
        "RestApiId": {
          "Ref": "ApiGatewayAdminThree"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "ApiGatewayAdminThreeProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "ApiGatewayAdminThreeDeployment6688e0289c"
        },
        "MethodSettings": [
          {
            "HttpMethod": "*",
            "LoggingLevel": "Info",
            "ResourcePath": "/*"
          }
        ],
        "RestApiId": {
          "Ref": "ApiGatewayAdminThree"
        },
        "StageName": "Prod",
        "TracingEnabled": true
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "ApiGatewayAdminTwo": {
      "Condition": "CreateProdResources",
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "paths": {},
          "swagger": "2.0"
        },
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "Name": "App-Prod-Web",
        "Parameters": {
          "endpointConfigurationTypes": "REGIONAL"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "ApiGatewayAdminTwoBasePathMapping": {
      "Condition": "CreateProdResources",
      "Properties": {
        "DomainName": {
          "Ref": "ApiGatewayDomainName3fd2dbd8f8"
        },
        "RestApiId": {
          "Ref": "ApiGatewayAdminTwo"
        },
        "Stage": {
          "Ref": "ApiGatewayAdminTwoProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMapping"
    },
    "ApiGatewayAdminTwoDeploymente4496c9f53": {
      "Condition": "CreateProdResources",
      "Properties": {
        "Description": "RestApi deployment id: e4496c9f5342d32f9172f98949d461d993b1c008",
        "RestApiId": {
          "Ref": "ApiGatewayAdminTwo"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "ApiGatewayAdminTwoProdStage": {
      "Condition": "CreateProdResources",
      "Properties": {
        "DeploymentId": {
          "Ref": "ApiGatewayAdminTwoDeploymente4496c9f53"
        },
        "MethodSettings": [
          {
            "HttpMethod": "*",
            "LoggingLevel": "Info",
            "ResourcePath": "/*"
          }
        ],
        "RestApiId": {
          "Ref": "ApiGatewayAdminTwo"
        },
        "StageName": "Prod",
        "TracingEnabled": true
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "ApiGatewayDomainName3fd2dbd8f8": {
      "Condition": "CreateProdResources",
      "Properties": {
        "DomainName": "admin.two.amazon.com",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/abc"
      },
      "Type": "AWS::ApiGateway::DomainName"
    },
    "ApiGatewayDomainName41bfc7f9c4": {
      "Properties": {
        "DomainName": "admin.three.amazon.com",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/abc"
      },
      "Type": "AWS::ApiGateway::DomainName"
    },
    "ApiGatewayDomainName5fe29fe649": {
      "Properties": {
        "DomainName": "admin.one.amazon.com",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/abc"
      },
      "Type": "AWS::ApiGateway::DomainName"
    },
    "RecordSetGroup370194ff6e": {
      "Properties": {
        "HostedZoneId": "abc123456",
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName5fe29fe649",
                  "RegionalDomainName"
                ]
              },
              "HostedZoneId": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName5fe29fe649",
                  "RegionalHostedZoneId"
                ]
              }
            },
            "Name": "admin.one.amazon.com",
            "Type": "A"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    },
    "RecordSetGroup81840409a4": {
      "Properties": {
        "HostedZoneId": "abc123456",
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName41bfc7f9c4",
                  "RegionalDomainName"
                ]
              },
              "HostedZoneId": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName41bfc7f9c4",
                  "RegionalHostedZoneId"
                ]
              }
            },
            "Name": "admin.three.amazon.com",
            "Type": "A"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    },
    "RecordSetGroupb3fa99c196": {
      "Condition": "CreateProdResources",
      "Properties": {
        "HostedZoneId": "abc123456",
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName3fd2dbd8f8",
                  "RegionalDomainName"
                ]
              },
              "HostedZoneId": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName3fd2dbd8f8",
                  "RegionalHostedZoneId"
                ]
              }
            },
            "Name": "admin.two.amazon.com",
            "Type": "A"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    }
  }
}

=== claytonbrown/serverless-application-model/tests/translator/output/api_with_custom_domain_route53_multiple_intrinsic_hostedzoneid.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "apigateway-2402\nSample SAM Template for apigateway-2402\n",
  "Parameters": {
    "MyHostedZoneId": {
      "Type": "String"
    }
  },
  "Resources": {
    "ApiGatewayAdminOne": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "paths": {},
          "swagger": "2.0"
        },
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "Name": "App-Prod-Web",
        "Parameters": {
          "endpointConfigurationTypes": "REGIONAL"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "ApiGatewayAdminOneBasePathMapping": {
      "Properties": {
        "DomainName": {
          "Ref": "ApiGatewayDomainName5fe29fe649"
        },
        "RestApiId": {
          "Ref": "ApiGatewayAdminOne"
        },
        "Stage": {
          "Ref": "ApiGatewayAdminOneProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMapping"
    },
    "ApiGatewayAdminOneDeployment90f9e9bb3f": {
      "Properties": {
        "Description": "RestApi deployment id: 90f9e9bb3ff69b4b71008da58841c770681ed84c",
        "RestApiId": {
          "Ref": "ApiGatewayAdminOne"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "ApiGatewayAdminOneProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "ApiGatewayAdminOneDeployment90f9e9bb3f"
        },
        "MethodSettings": [
          {
            "HttpMethod": "*",
            "LoggingLevel": "Info",
            "ResourcePath": "/*"
          }
        ],
        "RestApiId": {
          "Ref": "ApiGatewayAdminOne"
        },
        "StageName": "Prod",
        "TracingEnabled": true
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "ApiGatewayAdminThree": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "paths": {},
          "swagger": "2.0"
        },
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "Name": "App-Prod-Web",
        "Parameters": {
          "endpointConfigurationTypes": "REGIONAL"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "ApiGatewayAdminThreeBasePathMapping": {
      "Properties": {
        "DomainName": {
          "Ref": "ApiGatewayDomainName41bfc7f9c4"
        },
        "RestApiId": {
          "Ref": "ApiGatewayAdminThree"
        },
        "Stage": {
          "Ref": "ApiGatewayAdminThreeProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMapping"
    },
    "ApiGatewayAdminThreeDeployment127733f946": {
      "Properties": {
        "Description": "RestApi deployment id: 127733f94631341b13b3d91531d39f307d0b4700",
        "RestApiId": {
          "Ref": "ApiGatewayAdminThree"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "ApiGatewayAdminThreeProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "ApiGatewayAdminThreeDeployment127733f946"
        },
        "MethodSettings": [
          {
            "HttpMethod": "*",
            "LoggingLevel": "Info",
            "ResourcePath": "/*"
          }
        ],
        "RestApiId": {
          "Ref": "ApiGatewayAdminThree"
        },
        "StageName": "Prod",
        "TracingEnabled": true
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "ApiGatewayAdminTwo": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "paths": {},
          "swagger": "2.0"
        },
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "Name": "App-Prod-Web",
        "Parameters": {
          "endpointConfigurationTypes": "REGIONAL"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "ApiGatewayAdminTwoBasePathMapping": {
      "Properties": {
        "DomainName": {
          "Ref": "ApiGatewayDomainName3fd2dbd8f8"
        },
        "RestApiId": {
          "Ref": "ApiGatewayAdminTwo"
        },
        "Stage": {
          "Ref": "ApiGatewayAdminTwoProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMapping"
    },
    "ApiGatewayAdminTwoDeployment19f5544fe4": {
      "Properties": {
        "Description": "RestApi deployment id: 19f5544fe49037ecad607e6d0a584c3a252b6367",
        "RestApiId": {
          "Ref": "ApiGatewayAdminTwo"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "ApiGatewayAdminTwoProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "ApiGatewayAdminTwoDeployment19f5544fe4"
        },
        "MethodSettings": [
          {
            "HttpMethod": "*",
            "LoggingLevel": "Info",
            "ResourcePath": "/*"
          }
        ],
        "RestApiId": {
          "Ref": "ApiGatewayAdminTwo"
        },
        "StageName": "Prod",
        "TracingEnabled": true
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "ApiGatewayDomainName3fd2dbd8f8": {
      "Properties": {
        "DomainName": "admin.two.amazon.com",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/abc"
      },
      "Type": "AWS::ApiGateway::DomainName"
    },
    "ApiGatewayDomainName41bfc7f9c4": {
      "Properties": {
        "DomainName": "admin.three.amazon.com",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/abc"
      },
      "Type": "AWS::ApiGateway::DomainName"
    },
    "ApiGatewayDomainName5fe29fe649": {
      "Properties": {
        "DomainName": "admin.one.amazon.com",
        "EndpointConfiguration": {
          "Types": [
            "REGIONAL"
          ]
        },
        "RegionalCertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/abc"
      },
      "Type": "AWS::ApiGateway::DomainName"
    },
    "RecordSetGroupd28e0e19d0": {
      "Properties": {
        "HostedZoneId": {
          "Ref": "MyHostedZoneId"
        },
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName41bfc7f9c4",
                  "RegionalDomainName"
                ]
              },
              "HostedZoneId": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName41bfc7f9c4",
                  "RegionalHostedZoneId"
                ]
              }
            },
            "Name": "admin.three.amazon.com",
            "Type": "A"
          },
          {
            "AliasTarget": {
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName5fe29fe649",
                  "RegionalDomainName"
                ]
              },
              "HostedZoneId": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName5fe29fe649",
                  "RegionalHostedZoneId"
                ]
              }
            },
            "Name": "admin.one.amazon.com",
            "Type": "A"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    },
    "RecordSetGroupd9cb5a3e02": {
      "Properties": {
        "HostedZoneId": {
          "Fn::Sub": "{{MyHostedZoneId}}"
        },
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName3fd2dbd8f8",
                  "RegionalDomainName"
                ]
              },
              "HostedZoneId": {
                "Fn::GetAtt": [
                  "ApiGatewayDomainName3fd2dbd8f8",
                  "RegionalHostedZoneId"
                ]
              }
            },
            "Name": "admin.two.amazon.com",
            "Type": "A"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    }
  }
}
